import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./context/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#faf8ff",
        surface: "#faf8ff",
        "on-surface": "#131b2e",
        "on-surface-variant": "#424656",
        "on-background": "#131b2e",
        primary: "#0050cb",
        "on-primary": "#ffffff",
        "primary-container": "#0066ff",
        "on-primary-container": "#f8f7ff",
        "primary-fixed": "#dae1ff",
        "primary-fixed-dim": "#b3c5ff",
        secondary: "#006c49",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        tertiary: "#7f4f00",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-container": "#a06500",
        "surface-container-low": "#f2f3ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "outline-variant": "#c2c6d8",
        outline: "#727687",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "16px",
        lg: "32px",
        xl: "48px",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-tablet": "32px",
        gutter: "16px",
        base: "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "40px",
      },
      boxShadow: {
        bloom: "0 8px 24px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
} satisfies Config;
